pyproject.toml
src/app_model/__init__.py
src/app_model/_app.py
src/app_model/registries/_commands.py
src/app_model/registries/_keybindings.py
src/app_model/registries/_menus.py
src/app_model/registries/_register.py
src/app_model/types/__init__.py
src/app_model/types/_icon.py
src/app_model/types/_keybinding.py
src/app_model/types/_menu.py
src/app_model/types/_misc.py
tests/test_actions.py
tests/test_app.py

top level centralized `Application` that contains all the registries

feat: combine app model

---

src/app_model/registries/_commands_reg.py
src/app_model/types/_action.py
src/app_model/types/_utils.py
tests/conftest.py
tests/fixtures/fake_module.py
tests/test_app.py
tests/test_types.py

```python
Action(
id='some.command',
title="Some Title",
callback="my_module:some_function",  # resolve at calltime please
),
```

feat: allow callbacks as strings

---

docs/application.md
src/app_model/_app.py
src/app_model/registries/_commands_reg.py
tests/test_registries.py

makes it easier for applications to override their registry classes, and also adds a `raise_synchronous_exceptions` option (defaults to False) that, when True, will raise any exceptions encountered during `execute_command` in a synchronous context

feat: raise_synchronous option, and expose app classes

---

src/app_model/backends/qt/_qaction.py
src/app_model/types/_command_rule.py
tests/conftest.py
tests/test_qt/test_qmenu.py

Adds the ability to toggle  menu item based on a condition

feat: add toggled to command

---

src/app_model/backends/qt/_qaction.py
src/app_model/expressions/_expressions.py
src/app_model/types/_command_rule.py

this makes it possible to declare an action or menu item with `enablement: False` (perhaps based on an environment variable or setting or something) to immediately hide it

feat: eval expr when creating menus

---

src/app_model/backends/qt/_qkeymap.py
src/app_model/types/_keys/_keybindings.py
tests/test_keybindings.py

this is an idea PR to convert keybinding to a normal class instead of a base model to allow it to be represented properly in json and yaml without complicated workarounds

feat: convert keybinding to normal class

---

src/app_model/registries/_menus_reg.py

This changes the `MenusRegistry` class to use a dict in place of a list for the internal storage of menu items. The benefit here is when disposing it does not have to repeatedly call `list.remove`, which performs a linear search each time. Instead the dict acts as an ordered set and removing items takes constant time.
This is probably not an important optimization in general usage, but I believe it fixes a significant regression in napari test times. I think it's due to this `autouse` fixture introduced a few weeks ago: https://github.com/napari/napari/blob/1cc90a74211c6cbf3fc644da5866f9752cf1ac78/napari/conftest.py#L448
There may be other ways to fix/workaround it (maybe the fixture just needs better scoping?) so this PR is just meant to start a discussion.
Here's a chunk of some …

refactor: Use a dict (as an ordered set) instead of a list for menus registry

---

src/app_model/backends/qt/_qkeymap.py

fixes `unsupported operand type(s) for &: 'PySide6.QtCore.QKeyCombination' and 'KeyboardModifier'` on the newest pyside6
side-note: fixes in https://github.com/napari/superqt/pull/133 should get pyside6 tests working again

fix: fix unsupported operand

---

src/app_model/backends/qt/_qkeymap.py
tests/test_qt/test_qkeymap.py

yeah so i made an oopsie in https://github.com/pyapp-kit/app-model/pull/64 and only had the logic checking for modifier swaps... it now properly handles keycode swaps as well 😅

fix: Fix ctrl meta key swap (for real this time (i think))

---

.github/workflows/ci.yml
.github/workflows/cron.yml
pyproject.toml
src/app_model/backends/qt/__init__.py
src/app_model/backends/qt/_qmenu.py
tests/test_qt/test_qmenu.py

fixes #93 
while it helped reduce a little bit of code duplication, i was never particularly happy with the _MenuMixin anyway.  So this just removes it

fix: don't use mixin for menus

---

src/app_model/types/_keys/_standard_bindings.py

[Qt](https://doc.qt.io/qt-6/qkeysequence.html#standard-shortcuts) suggests this shortcut for MacOS, with no bindings for Win or Linux. [VS code](https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-reference) uses this shortcut for all platforms.
I have amended primary key binding for 'preferences' to be `Ctrl + ,`. 
Another option is to follow Qt and only set keybinding to be this for Mac, leaving rest as None. Happy to change.

fix: Amend preferences `StandardKeyBinding`

---

src/app_model/expressions/_expressions.py

Closes #106 
Have added a 'includes ..' to note less well known operators, can remove this.

docs: Move `_expressions.py` docstring to be included in documentation

---

src/app_model/expressions/_context.py
tests/test_context/test_context.py

when a context is made up of other contexts, its events are not propagated correctly:
```python
a = Context()
b = Context()
c = Context(a, b)
c.changed.connect(print)
a['42'] = 42
```

fix: properly connect events for Contexts comprised of other Contexts

---

src/app_model/types/_menu_rule.py
tests/test_actions.py

In many cases, an Action may be declared with a menu as :
```python
types.Action(
id="copy",
menus=[{"id": MenuId.EDIT}],
),
```
this PR allows that to be simply
```python
types.Action(
id="copy",
menus=[MenuId.EDIT],
),
```

feat: accept single string id as menu key in Actions.menus

---

src/app_model/backends/qt/_qaction.py
src/app_model/types/_command_rule.py
tests/test_qt/test_qactions.py

controls whether individual Action icons should be visible in menus.  Still controllable directly in the qt backend with `Qt.ApplicationAttribute.AA_DontShowIconsInMenus`

feat: add `CommandRule.icon_visible_in_menu`

---

src/app_model/backends/qt/_qmenu.py

This fixes #147 
There may be other/better ways to fix it.  Specifically, we could add a new `menus_removed` signal to the MenuRegistry, and emit that instead of `menu_changed` here: https://github.com/pyapp-kit/app-model/blob/0049cb81e3e7a6825f325320fb7fa28c5023b372/src/app_model/registries/_menus_reg.py#L71
but, until I'm sure that that doesn't have unintended side effects, this should at least catch the case of trying to rebuild a submenu that has just been disposed of.

fix: catch runtime error on QModelSubmenu cleanup

---

pyproject.toml
src/app_model/_app.py
src/app_model/backends/qt/_qaction.py
src/app_model/expressions/__init__.py
src/app_model/expressions/_context.py
tests/conftest.py
tests/test_app.py

This PR adds an `Application.context` attribute.  It can serve as a natural place for applications to put a top level context (and, as usual, they can spawn children contexts with `context.new_child`).
it does not yet hook up context.changed signals to anything in the Qt backend.  mostly because I think more consideration of context "scoping" is necessary.  For example, it's not obvious that `app.context` is the "correct" context to pass to one of the `update_from_context` methods... it might be a more narrowly scoped child context provided by the user.

feat: add top level Application.context

---

.github/workflows/ci.yml

updates tests to use:
- https://github.com/pyapp-kit/workflows/blob/main/.github/workflows/test-pyrepo.yml for running tests
- https://github.com/pyapp-kit/workflows/blob/main/.github/workflows/test-dependents.yml - for testing things that depend on app-model, like napari
closes #129

ci: Update CI workflow to include reusable test

---

mkdocs.yml
src/app_model/__init__.py
src/app_model/_app.py
src/app_model/expressions/_expressions.py
src/app_model/registries/_register.py
src/app_model/types/_keys/_keybindings.py

This adds the functional form of `register_action` (the one that supports decorator usage) as a top level export.
It also adds the full overload to the `Application.register_action` method.  This isn't technically adding a new form or new functionality, just exposing it

feat: export register_action function at top level

---

.github/workflows/ci.yml

Add more test to napari test to easier early find incompatybilites and earlier prepare napari repository for changes.

ci: Add testing of napari/utils/_tests/test_key_bindings.py

---

src/app_model/backends/qt/_qkeymap.py

We're trying to Goldilocks a pyside6 version for napari tests.
Recently (https://github.com/napari/napari/pull/6738) when testing with pyside6 6.3.1, we got this failure:
https://github.com/napari/napari/actions/runs/8303510051/job/22727974608?pr=6738#step:12:209
```
Traceback (most recent call last):
File "/home/runner/work/napari/napari/napari/_qt/widgets/qt_keyboard_settings.py", line 685, in keyPressEvent
kb = qkeysequence2modelkeybinding(event_keyseq)
File "/home/runner/work/napari/napari/.tox/py39-linux-pyside6-cov/lib/python3.9/site-packages/app_model/backends/qt/_qkeymap.py", line 316, in qkeysequence2modelkeybinding
parts = [SimpleKeyBinding.from_int(qkeycombo2modelkey(x)) for x in iter(key)]
File "/home/runner/work/napari/napari/.tox/py39-linux-pyside6-cov/lib/python3.9/site-pack …
```

fix: handle qmods like QT5 for pyside6 not 6.4

---

.pre-commit-config.yaml
src/app_model/_app.py
src/app_model/backends/qt/__init__.py
src/app_model/expressions/__init__.py
src/app_model/expressions/_context_keys.py
src/app_model/expressions/_expressions.py
src/app_model/registries/__init__.py
src/app_model/registries/_register.py
src/app_model/types/__init__.py
src/app_model/types/_keys/_key_codes.py
src/app_model/types/_utils.py
tests/test_context/test_context.py

forgot to add the format bit to pre-commit

chore: add format to pre-commit

---

src/app_model/backends/qt/_qaction.py
src/app_model/backends/qt/_qmenu.py
tests/test_qt/test_qactions.py

In napari tests I got segfaults, after local debugs it points to lambda that are modified in this PR. 
In general, using the method is safer, as qt will not try to trigger the method of destroyed objects.

fix: Do not use lambda in QMenuItemAction.destroyed callback

---

.github/workflows/ci.yml
src/app_model/registries/__init__.py
src/app_model/registries/_commands_reg.py
src/app_model/registries/_keybindings_reg.py
src/app_model/registries/_menus_reg.py
src/app_model/registries/_register.py
tests/test_command_registry.py

This PR moves some of the logic in the `register_action` function into methods on the registries themselves.  This will make it easier for custom subclasses of registries to control exactly how they register actions.  
It has some relatively inconsequential other stuff, like making `RegisteredCommand` immutable and public

feat: give registries more control over registration of actions

---

src/app_model/expressions/_expressions.py
tests/test_context/test_expressions.py

This PR moves the compilation of the expression to the `__init__`... this should make evaluating expressions up to ~30x faster (based on local testing).
It also allows passing kwargs: `expr.eval(x=1, z=3)` instead of `expr.eval({"x": 1, "z": 3})` , though it will be *slightly* slower (sub-microsecond)

perf: faster `Expr.eval` by precompiling expressions

---

src/app_model/expressions/_expressions.py
tests/test_context/test_expressions.py

cc @hanjinliu this would add support for various Sequence objects to expressions. closes #201 
I need to think about this a bit, and look into possible problems.

feat: add Sequences to expressions

---

src/app_model/types/__init__.py
src/app_model/types/_keys/_keybindings.py
tests/test_keybindings.py

closes #209 
modifier keys can now be expressed as:
```python
_re_ctrl = re.compile(r"(ctrl|control|ctl|⌃)[\+|\-]")
_re_shift = re.compile(r"(shift|⇧)[\+|\-]")
_re_alt = re.compile(r"(alt|opt|option|⌥)[\+|\-]")
_re_meta = re.compile(r"(meta|super|win|windows|⊞|cmd|command|⌘)[\+|\-]")
```

feat: more flexible keybinding parser

---

src/app_model/registries/_keybindings_reg.py
tests/test_registries.py

closes #206
Adds a `filter_keybinding` (not 100% on name) attr to `KeyBindingRegistry`, which takes `Callable[[KeyBinding], str]` - if str is empty the keybinding is valid otherwise error message str should be returned.
Just a start, happy to take any feedback.
Will update docs once code ready.

feat: Add `filter_keybinding` to `KeyBindingRegistry`

---

src/app_model/types/_keys/_standard_bindings.py

I just discovered the very cool StandardKeyBindings while adding Zoom keybindings in napari.
In this PR I'm just adding the `command/control-0` to reset zoom as a standard keybinding, sometimes called OriginalSize (Qt), Actual Size (macOS), etc. but a consistent pattern on macOS and Windows and in Qt (https://doc.qt.io/qtcreator/creator-keyboard-shortcuts.html#image-viewer-shortcuts).

feat: Include command/control-0 for OriginalSize in StandardKeyBindings

---

.github/workflows/ci.yml
demo/model_app.py
demo/multi_file/actions.py
pyproject.toml
src/app_model/_app.py
src/app_model/backends/qt/_qaction.py
src/app_model/backends/qt/_qkeymap.py
src/app_model/backends/qt/_qmainwindow.py
src/app_model/backends/qt/_qmenu.py
src/app_model/expressions/_context.py
src/app_model/expressions/_context_keys.py
src/app_model/expressions/_expressions.py
src/app_model/registries/_commands_reg.py
src/app_model/registries/_keybindings_reg.py
src/app_model/registries/_menus_reg.py
src/app_model/types/_action.py
src/app_model/types/_icon.py
src/app_model/types/_keybinding_rule.py
src/app_model/types/_keys/_keybindings.py
src/app_model/types/_menu_rule.py
tests/conftest.py
tests/test_actions.py

build: drop 3.8 and add 3.13

---

.pre-commit-config.yaml
src/app_model/expressions/_context_keys.py
src/app_model/expressions/_expressions.py
src/app_model/types/__init__.py
tests/test_context/test_expressions.py

this allows for directly providing the type to which a Name expression evaluates to:
```python
from app_model.expressions import Name
is_running = Name("is_running", bound=bool)
reveal_type(is_running.eval())  # Revealed type is "builtins.bool"
```
also updates pre-commit

feat: allow explicit variable bound to be passed to Name

---

src/app_model/_app.py
src/app_model/registries/_register.py
src/app_model/types/__init__.py
tests/test_app.py

This PR allows one to query all of the actions that have been registered.  Currently, because an action is ultimately a wrapper around commands, menu placements, and keybindings... the registered action gets broken up and contributed to each registry.  This PR just lets you remember how they all came in together.  It's an immutable mapping proxy.

feat: add `registered_actions` to Application

---

src/app_model/backends/qt/_qmenu.py

Closes #245
I tested it locally, do not have an idea how to test it on CI.

fix: Use QApplication instance as a parent of global actions

---

src/app_model/_app.py
tests/test_qt/test_qmainwindow.py

fix: order of menu registration to come after keybindings registration

---

pyproject.toml

The pytest-qt 4.5.0 drops pyside2 support. 
I suggest using pytest-qt in version to 4.4.0 for python 3.10. 
As we merged PySide6 support in napari a short time ago, I expect to drop PySide2 in the following months.

chore: Pin `pytest-qt` on python 3.10 to fix pyside2 tests
